/*
Deployment script for PNSMS_LR

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

USE PNSMS;


GO
/*
The column [dbo].[Images].[RefCode] is being dropped, data loss could occur.

The column [dbo].[Images].[RefTypeId] on table [dbo].[Images] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
*/

IF EXISTS (select top 1 1 from [dbo].[Images])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
PRINT N'Starting rebuilding table [dbo].[Images]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_Images] (
    [Id]              INT             IDENTITY (1, 1) NOT NULL,
    [RefTypeId]       INT             NOT NULL,
    [RefPrimaryKey]   INT             NOT NULL,
    [ImageBinaryData] VARBINARY (MAX) NULL,
    [ImageCaption]    NVARCHAR (MAX)  NULL,
    [ImageUrl]        NVARCHAR (MAX)  NULL,
    [FileExt]         NVARCHAR (50)   NULL,
    [IsActive]        BIT             NOT NULL,
    [LastUpdatedTime] DATETIME        NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_Images] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[Images])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_Images] ON;
        INSERT INTO [dbo].[tmp_ms_xx_Images] ([Id], [RefPrimaryKey], [ImageBinaryData], [ImageCaption], [ImageUrl], [IsActive], [LastUpdatedTime])
        SELECT   [Id],
                 [RefPrimaryKey],
                 [ImageBinaryData],
                 [ImageCaption],
                 [ImageUrl],
                 [IsActive],
                 [LastUpdatedTime]
        FROM     [dbo].[Images]
        ORDER BY [Id] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_Images] OFF;
    END

DROP TABLE [dbo].[Images];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_Images]', N'Images';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_Images]', N'PK_Images', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [dbo].[Images].[IX_Images]...';


GO
CREATE NONCLUSTERED INDEX [IX_Images]
    ON [dbo].[Images]([RefTypeId] ASC, [RefPrimaryKey] ASC);


GO
PRINT N'Creating [dbo].[ImageTypes]...';


GO
CREATE TABLE [dbo].[ImageTypes] (
    [Id]   INT            NOT NULL,
    [Name] NVARCHAR (128) NOT NULL,
    CONSTRAINT [PK_ImageTypes] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[FK_Images_ImageTypes]...';


GO
ALTER TABLE [dbo].[Images] WITH NOCHECK
    ADD CONSTRAINT [FK_Images_ImageTypes] FOREIGN KEY ([RefTypeId]) REFERENCES [dbo].[ImageTypes] ([Id]);


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE PNSMS;


GO
ALTER TABLE [dbo].[Images] WITH CHECK CHECK CONSTRAINT [FK_Images_ImageTypes];


GO
PRINT N'Update complete.';

INSERT [dbo].[ImageTypes] ([Id], [Name]) VALUES (11, N'Institute Banner')
INSERT [dbo].[ImageTypes] ([Id], [Name]) VALUES (12, N'Institute Logo')
INSERT [dbo].[ImageTypes] ([Id], [Name]) VALUES (13, N'Institute Landing Slider')
INSERT [dbo].[ImageTypes] ([Id], [Name]) VALUES (14, N'UserInfo Photo')
INSERT [dbo].[ImageTypes] ([Id], [Name]) VALUES (15, N'Notice')
INSERT [dbo].[ImageTypes] ([Id], [Name]) VALUES (16, N'Events')
INSERT [dbo].[ImageTypes] ([Id], [Name]) VALUES (17, N'Gallery')
INSERT [dbo].[ImageTypes] ([Id], [Name]) VALUES (18, N'Galley_Small')

update dbo._Migration set LastUpdate='0010'

GO
